name: Main Workflow

on:
  push:
  workflow_dispatch:

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    uses: ./.github/workflows/packagev4.yml
    with:
      version: ${{ matrix.python-version }}
  deposition:
    needs: version-matrix
    runs-on: ubuntu-latest
    if: always()
    env:
      WORKFLOW_ID: ${{ github.run_id }}
      TZ: America/New_York
    steps:
      - name: Set env vars
        run: |
          export ZENODO_TOKEN=${{ secrets.ZENODO_TOKEN }}
          echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >> $GITHUB_ENV

          export GHA_TOKEN=${{github.token}}
          echo "GHA_TOKEN=${GHA_TOKEN}" >> $GITHUB_ENV

          export GH_TOKEN=${{github.token}}
          echo "GH_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install YAML CLI tools
        run: |
          python3 -m pip install shyaml
      - name: download artifacts v2
        run: |
          set -vxeuo pipefail
          python3 parse_for_artifacts.py -a "${{ env.WORKFLOW_ID }}"
      - name: Upload artifacts to Zenodo
        run: |
          python3 -m pip install requests
          python3 upload_on_success.py -a "${{ env.WORKFLOW_ID }}"


