name: Main Workflow

on:
  push:

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    uses: ./.github/workflows/packagev3.yml
    with:
      version: ${{ matrix.python-version }}


